[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/src/main.ts" # Verifica que esta ruta sea correcta y necesaria.
  status = 200

[environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
