[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
from = '/_next/image/*'
query = { q = ':quality', url = ':url', w = ':width' }
to = '/.netlify/images?url=:url&w=:width&q=:quality'
status = 200
force = true

[environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
